version: '3'
services:
  app:
    build: docker/node
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./app/:/app/
    working_dir: /app/
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true